name: beautiful_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^0.5.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/auth/image_01.png
   - assets/auth/image_02.png
   - assets/auth/logo.png
   - assets/auth/logo_egs.png

  fonts:
    - family: CustomIcons
      fonts: 
        - asset: assets/auth/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/auth/Poppins-Bold.ttf

    
    - family: Poppins-Medium
      fonts: 
        - asset: assets/auth/Poppins-Medium.ttf