name: beautiful_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^0.5.2
  gradient_text: ^1.0.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:

  # auth
  
   - assets/auth/image_01.png
   - assets/auth/image_02.png
   - assets/auth/logo.png
   - assets/auth/logo_egs.png

  # onboarding

   - assets/onboarding/illustration.png
   - assets/onboarding/illustration2.png
   - assets/onboarding/illustration3.png

  fonts:
  
  # auth

    - family: CustomIcons
      fonts: 
        - asset: assets/auth/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/auth/Poppins-Bold.ttf

    
    - family: Poppins-Medium
      fonts: 
        - asset: assets/auth/Poppins-Medium.ttf

    
  # onboarding

    - family: Montserrat-Black
      fonts:
        - asset: assets/onboarding/Montserrat-Black.ttf
   
    - family: Montserrat-Medium
      fonts:
        - asset: assets/onboarding/Montserrat-Medium.ttf